general {
    # Garante que não teremos várias instâncias do hyprlock abertas ao mesmo tempo
    lock_cmd = pidof hyprlock || hyprlock       
    
    # Bloqueia a tela imediatamente antes do sistema suspender (ex: fechar a tampa do notebook)
    before_sleep_cmd = loginctl lock-session    
    
    # Garante que a tela vai ligar quando o sistema acordar
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1º Estágio: Bloquear a tela
listener {
    timeout = 600                                 # 5 minutos em segundos (5 * 60)
    on-timeout = loginctl lock-session            # Usa o loginctl para chamar o lock_cmd
}

# 2º Estágio: Desligar o monitor
listener {
    timeout = 630                                 # 5 minutos e 30 segundos
    on-timeout = hyprctl dispatch dpms off        # Desliga a tela para economizar energia
    on-resume = hyprctl dispatch dpms on          # Religa a tela quando você mexer o mouse
}

# 3º Estágio: Suspender (Dormir)
listener {
    timeout = 1800                                 # 30 minutos
    on-timeout = systemctl suspend                # Coloca o computador para dormir
}
