-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "breeze_cursors")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
	cursor = {
		enable_hyprcursor = false,
	},
	dwindle = {
		smart_split = false,
	},
	general = {
		border_size = 2,
	},
	input = {
		repeat_delay = 400,
		repeat_rate = 50,
		sensitivity = 0.2,
	},
})

-- Bezier curves
hl.curve("easeIn", { type = "bezier", points = { { 0.42, 0.0 }, { 1.0, 1.0 } } })
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1.0 }, { 0.32, 1.0 } } })

-- Animations
hl.animation({
	leaf = "windows",
	enabled = true,
	speed = 4.79,
	spring = "easy",
	style = "slide",
})
hl.animation({
	leaf = "windowsMove",
	enabled = true,
	speed = 4.79,
	spring = "easy",
	style = "slide",
})
hl.animation({
	leaf = "layers",
	enabled = true,
	speed = 3.81,
	bezier = "easeOutQuint",
})
hl.animation({
	leaf = "workspaces",
	enabled = true,
	speed = 1.94,
	bezier = "easeIn",
	style = "slidefade",
})

-- Layer rules
hl.layer_rule({
	match = {
		namespace = "waybar",
	},
	xray = true,
})
