color0 #282a29
color1 #fd4663
color2 #67e4a6
color3 #d6b85c
color4 #6699cc
color5 #93ecc0
color6 #e9d496
color7 #f2f3f2
color8 #666a68
color9 #fd4663
color10 #67e4a6
color11 #d6b85c
color12 #6699cc
color13 #93ecc0
color14 #e9d496
color15 #f2f3f2

cursor                #f2f3f2
cursor_text_color     #1e1f1e
background            #1e1f1e
foreground            #f2f3f2
selection_foreground  #afb6b3
selection_background  #282a29
active_border_color   #67e4a6
inactive_border_color #282a29
url_color             #67e4a6

active_tab_foreground   #18251f
active_tab_background   #67e4a6
inactive_tab_foreground #afb6b3
inactive_tab_background #282a29
cursor_trail_color      #afb6b3
